site_name: A New Design of Healthcare.gov
extra_css: ['css/extra.css']
pages:
  - [index.md, "Executive Summary"]
  - [introduction.md, Introduction]
  - [architecture.md, Architecture]
  - [conclusion.md, Conclusion]
